image : python:3.10

stages:
    - code-check

before_script:
    - apt update
    - python3.10 -m pip install pylint
    - python3.10 -m pip install pytest
    - cd ..

code-analysis:
    stage: code-check
    script :
        - pylint --recursive=y riverapp/src --disable=R0901,W0613,C0114,E0611 --fail-under=3 --class-attribute-naming-style=snake_case
        - python -m pytest riverapp/tests/riverapp_test/
