image: continuumio/miniconda3

stages:
    # - Linting
    - Languages

before_script:
    # - sudo apt-get update
    # # install all required libraries using existing conda environment requirements file:
    # - conda env create -f envs/pyorc-dev.yml
    # - conda init bash
    # - source ~/.bashrc
    # - conda activate pyorc-dev


# pylint:
#     stage: Linting
#     script: 
#         - pylint --recursive=y riverapp --disable=R0901,W0613,C0114,E0611 --fail-under=7 --class-attribute-naming-style=snake_case

python-hello-world:
    stage: Languages
    # image : python3.10
    script :
        - sudo python3.10 -m pip install pylint
        - cd ..
        - pylint --recursive=y riverapp --disable=R0901,W0613,C0114,E0611 --fail-under=7 --class-attribute-naming-style=snake_case