from cv2 import VideoCapture, flip, CAP_PROP_POS_FRAMES, CAP_PROP_FPS
from os.path import exists
from matplotlib import pyplot as plt
from io import BytesIO
import numpy as np

from kivy.uix.image import Image
from kivy.graphics.texture import Texture


def get_video_frame(video_path: str, time: int | float = 0) -> list:
    """ Retrieve a frame from a video

    You can use this function to get a specific frame from a video.
    It supports the same video as the cv2 package.

    Parameters
    ----------
    video_path : str
        The path where is the video saved

    time : int, float, optional
        Video time in second where the frame you want is
        Default : 0

    Returns
    -------
    list
        Video frame

    Raises
    ------
    ValueError
        If video_path or time does not respect their respective type

    FileNotFoundError
        If video_path is not found

    IOError
        If the video can not be loaded or read
    """

    if not isinstance(video_path, str):
        raise ValueError(f"video_path must be a string: {video_path}")

    if not isinstance(time, (float, int)):
        raise ValueError(f"time must be an int or a float: {time}")

    if not exists(video_path):
        raise FileNotFoundError(f"Could not find {video_path}")
    

    video_capture: VideoCapture = VideoCapture(video_path)
    
    if not video_capture.isOpened():
        raise IOError(f"Could not load {video_path}")
    
    video_capture.set(CAP_PROP_POS_FRAMES, int(time * video_capture.get(CAP_PROP_FPS)))
    
    success, frame = video_capture.read()
    
    video_capture.release()

    if not success:
        raise IOError(f"Could not read {video_path}")

    return frame

def video_to_image(video_path: str, time: int | float = 0) -> Image:
    """Convert a video frame to a kivy Image
    
    This function get a frame with the get_video_frame and convert it into
    a usable kivy Image

    Parameters
    ----------
    video_path : str
        The path where is the video saved.

    time : int, float, optional
        Video time in second where the frame you want is
        Default : 0

    Returns
    -------
    Image
        The video frame converted into a kivy Image

    Raises
    ------
    ValueError
        If video_path or time does not respect their respective type

    FileNotFoundError
        If video_path is not found

    IOError
        If the video can not be loaded or read
    """
    
    frame = get_video_frame(video_path, time)
    
    flipped_frame = flip(frame, 0)
    height, width, _ = flipped_frame.shape
    texture = Texture.create(size=(width, height))
    texture.blit_buffer(flipped_frame.tobytes(), colorfmt='bgr', bufferfmt='ubyte')

    return Image(texture=texture, size=(width, height), fit_mode="contain")


def plot_to_image(plot: plt) -> Image:
    """Convert a matplotlib plot to a kivy Image
    
    This function use a plot generated by matplotlib and convert it into a
    kivy Image

    Parameters
    ----------
    plot : plt
        The matplotlib to convert

    Returns
    -------
    Image
        The plot converted into a kivy Image

    """
    
    image_buffer: BytesIO = BytesIO()
    
    plot.savefig(image_buffer, format="png")
    plot.close()
    image_buffer.seek(0)

    # Load image data from the BytesIO object
    image_data = plt.imread(image_buffer)
    height, width, _ = image_data.shape

    # Invert the image vertically
    image_data = np.flipud(image_data)

    # Convert the image into values from 0 to 255 (8 bits) 
    image_data = (image_data * 255).astype(np.uint8)

    # Create texture from image data
    texture = Texture.create(size=(width, height), colorfmt='rgba')
    texture.blit_buffer(image_data.flatten(), colorfmt='rgba', bufferfmt='ubyte')
    
    image_buffer.close()

    return Image(texture=texture, size=(width, height), fit_mode="contain")
    

    

    
